/**
 * ProofGreen Disclaimer Service
 *
 * Provides standardized liability disclaimers for all reports and data.
 * CRITICAL: These disclaimers must appear on ALL generated reports.
 */

/**
 * Standard disclaimer for all ESG reports
 */
const REPORT_DISCLAIMER = `
DISCLAIMER: This report is provided for informational purposes only. ProofGreen
does not provide legal, regulatory, or compliance advice. Data accuracy is the
responsibility of the user. Consult EPA-certified professionals, legal counsel,
or compliance experts for regulatory matters. ProofGreen makes no warranties
regarding the accuracy or completeness of this data.
`.trim();

/**
 * Short version for UI displays
 */
const SHORT_DISCLAIMER = 'Data for informational purposes only. Not legal/compliance advice.';

/**
 * AI analysis disclaimer
 */
const AI_DISCLAIMER = `
AI ANALYSIS NOTICE: This analysis was generated using artificial intelligence and
requires user verification. AI estimates may not be accurate. Users must verify
all items, weights, and categories against actual documentation (scale readings,
weight tickets, disposal receipts) before submission. ProofGreen is not responsible
for inaccuracies in AI-generated data that has not been properly verified by the user.
`.trim();

/**
 * Weight estimation disclaimer
 */
const WEIGHT_DISCLAIMER = `
WEIGHT ESTIMATES: AI-generated weight estimates are approximations only. Actual
weights must be obtained from certified scales, weight tickets, or disposal facility
receipts. Do not rely on AI estimates for regulatory reporting or contractual obligations.
`.trim();

/**
 * Carbon offset disclaimer
 */
const CARBON_DISCLAIMER = `
CARBON OFFSET CALCULATIONS: Carbon offset estimates are based on EPA emissions factors
and industry-standard methodologies. Actual carbon savings may vary based on regional
grid composition, recycling facility efficiency, and other factors. These calculations
are estimates and should not be used for carbon credit certification without third-party
verification.
`.trim();

/**
 * Regulatory compliance disclaimer
 */
const COMPLIANCE_DISCLAIMER = `
REGULATORY COMPLIANCE: ProofGreen tracks and reports ESG metrics but does not guarantee
compliance with any federal, state, or local regulations. Users are responsible for
ensuring their operations comply with all applicable environmental regulations, including
but not limited to EPA, OSHA, and state environmental agency requirements. Consult with
qualified compliance professionals for regulatory guidance.
`.trim();

/**
 * Data retention disclaimer
 */
const DATA_DISCLAIMER = `
DATA HANDLING: User-provided data is stored in accordance with our Privacy Policy.
ProofGreen retains job data for reporting purposes and may anonymize and aggregate
data for industry benchmarking. Users are responsible for ensuring they have proper
authorization to submit customer and job information to the platform.
`.trim();

/**
 * Get all disclaimers for a full report
 */
function getFullReportDisclaimers() {
  return {
    main: REPORT_DISCLAIMER,
    sections: {
      ai: AI_DISCLAIMER,
      weight: WEIGHT_DISCLAIMER,
      carbon: CARBON_DISCLAIMER,
      compliance: COMPLIANCE_DISCLAIMER,
      data: DATA_DISCLAIMER
    },
    footer: `
Report generated by ProofGreen (https://proofgreen.io)
${new Date().toISOString().split('T')[0]}

${REPORT_DISCLAIMER}
    `.trim()
  };
}

/**
 * Get disclaimer for specific report type
 */
function getDisclaimerForReportType(reportType) {
  const disclaimers = {
    job_report: [REPORT_DISCLAIMER, WEIGHT_DISCLAIMER, CARBON_DISCLAIMER],
    esg_summary: [REPORT_DISCLAIMER, COMPLIANCE_DISCLAIMER, CARBON_DISCLAIMER],
    ai_analysis: [AI_DISCLAIMER, WEIGHT_DISCLAIMER],
    carbon_report: [REPORT_DISCLAIMER, CARBON_DISCLAIMER],
    compliance_report: [REPORT_DISCLAIMER, COMPLIANCE_DISCLAIMER],
    public_report: [REPORT_DISCLAIMER, SHORT_DISCLAIMER]
  };

  return disclaimers[reportType] || [REPORT_DISCLAIMER];
}

/**
 * Format disclaimer for PDF reports
 */
function formatForPDF() {
  return {
    title: 'Important Disclaimers',
    content: REPORT_DISCLAIMER,
    fontSize: 8,
    color: '#666666',
    margin: { top: 10, bottom: 10 }
  };
}

/**
 * Format disclaimer for email reports
 */
function formatForEmail() {
  return `
---
${REPORT_DISCLAIMER}

For questions about this report, contact support@proofgreen.io
  `.trim();
}

/**
 * Attestation text for user confirmation
 */
const ATTESTATION_TEXT = `
I certify that:
1. The data provided is accurate to the best of my knowledge
2. I have verified weights with documentation (scale tickets, receipts, etc.)
3. I understand ProofGreen provides data tracking only and does not provide legal or regulatory compliance advice
4. I am authorized to submit this information on behalf of my company
5. I have read and agree to ProofGreen's Terms of Service and Privacy Policy
`.trim();

/**
 * Get attestation for form display
 */
function getAttestationConfig() {
  return {
    text: ATTESTATION_TEXT,
    checkboxLabel: 'I confirm all the above statements are true',
    required: true,
    errorMessage: 'You must confirm the attestation before submitting'
  };
}

module.exports = {
  REPORT_DISCLAIMER,
  SHORT_DISCLAIMER,
  AI_DISCLAIMER,
  WEIGHT_DISCLAIMER,
  CARBON_DISCLAIMER,
  COMPLIANCE_DISCLAIMER,
  DATA_DISCLAIMER,
  ATTESTATION_TEXT,
  getFullReportDisclaimers,
  getDisclaimerForReportType,
  formatForPDF,
  formatForEmail,
  getAttestationConfig
};
